### ISSUE TITLE
roblox cookie

### ISSUE THREAD

**Issue by antiszoc2** [Smug246/Luna-Grabber#125]
everything works well, but its not logs roblox cookies for me. the file is empty, and i get nothing.

**Comment by antiszoc2** [comment]
Traceback (most recent call last):
  File "requests\models.py", line 971, in json
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 3 column 1 (char 4)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ImageGrabber.py", line 980, in <module>
  File "ImageGrabber.py", line 86, in Luna
  File "ImageGrabber.py", line 69, in main
  File "ImageGrabber.py", line 243, in __init__
  File "ImageGrabber.py", line 483, in upload
  File "ImageGrabber.py", line 357, in robloxinfo
  File "requests\models.py", line 975, in json
requests.exceptions.JSONDecodeError: Expecting value: line 3 column 1 (char 4)

this is what i get.

**Comment by Smug246** [comment]
check cookies.txt and tell me if there's a roblox cookie there

**Comment by Ilikedogslol3** [comment]
nothing shows up in roblox cookies

**Comment by Smug246** [comment]
> nothing shows up in roblox cookies

does your roblox cookie show up in cookies.txt

**Comment by Ilikedogslol3** [comment]
No

**Comment by Smug246** [comment]
> No

that just means that it couldnt get your roblox cookie from your browser because its not there

**Comment by Ilikedogslol3** [comment]
oh ok

**Comment by Ilikedogslol3** [comment]
also just letting you know the injection is broken because they can relogin and it doesnt send another token

**Comment by Ilikedogslol3** [comment]
also it doesn't get passwords only the token once

**Comment by Smug246** [comment]
it's only the injection that gets the password it won't get the password with the email
