### ISSUE TITLE
Traceback issue 

### ISSUE THREAD

**Issue by iamhykuuu** [Smug246/Luna-Grabber#127]
Traceback (most recent call last):
  File "logtest.py", line 1, in <module>
  File "<string>", line 4, in <module>
  File "<string>", line 1, in <module>
  File "<string>", line 980, in <module>
  File "<string>", line 86, in Luna
  File "<string>", line 61, in main
  File "requests\api.py", line 115, in post
  File "requests\api.py", line 59, in request
  File "requests\sessions.py", line 573, in request
  File "requests\sessions.py", line 484, in prepare_request
  File "requests\models.py", line 368, in prepare
  File "requests\models.py", line 439, in prepare_url
requests.exceptions.MissingSchema: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?
 how do i fix this? 
![immagine_2023-02-11_151456369](https://user-images.githubusercontent.com/124066743/218262715-0e547fe0-d6dc-4e64-8570-ee6a5a01a664.png)

**Comment by Smug246** [comment]
it means you didn't add a webhook. make sure you add a webhook and press check webhook before adding options or building it

**Comment by iamhykuuu** [comment]
Thank you sm for the answear but i do add webhook, and i press check and it says that this works. WHat can i do?

**Comment by Smug246** [comment]
are you definitely checking the webhook before you tick any options. sometimes it gets bugged and doesn't add it to the dictionary which means it doesn't get added to the file. you can check by building it as a py editing the file then looking for the webhook at the top. if it's not there then that's why
