### ISSUE TITLE
Please help me 

### ISSUE THREAD

**Issue by JustLmr** [Smug246/Luna-Grabber#130]
hey what's up man i get this error when i select them
 (systeminfo obfuscation,roblox info,browser info,wifi info,discord info,file pumper[30mb])
why does the problem occur 

<img width="200" alt="Ekran görüntüsü_20230212_160951" src="https://user-images.githubusercontent.com/88000765/218313323-64146343-8b1c-434c-bb8b-67dc9203a6c0.png">

**Comment by Smug246** [comment]
can you paste the full error

**Comment by Emirekicii** [comment]
Traceback (most recent call last):
  File "requests\models.py", line 971, in json
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 3 column 1 (char 4)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "AntiHileler.py", line 1, in <module>
  File "<string>", line 4, in <module>
  File "<string>", line 1, in <module>
  File "<string>", line 980, in <module>
  File "<string>", line 86, in Luna
  File "<string>", line 69, in main
  File "<string>", line 243, in __init__
  File "<string>", line 483, in upload
  File "<string>", line 357, in robloxinfo
  File "requests\models.py", line 975, in json
requests.exceptions.JSONDecodeError: Expecting value: line 3 column 1 (char 4)

**Comment by Smug246** [comment]
check cookies.txt and see if your roblox one is there

**Comment by Emirekicii** [comment]
yes the file you specified exists but it is empty

**Comment by Smug246** [comment]
simply means it couldn't grab any cookies. what browser do u use

**Comment by Emirekicii** [comment]
I am using Chrome and the defender feature is not used
