### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by NewMicahLangley** [Smug246/Luna-Grabber#151]
Traceback (most recent call last):
  File "C:\Users\New MIcah Langley\Desktop\Luna-Grabber-main\luna.py", line 1006, in <module>
    Luna(__CONFIG__["webhook"])
  File "C:\Users\New MIcah Langley\Desktop\Luna-Grabber-main\luna.py", line 106, in Luna
    proc(webhook)
  File "C:\Users\New MIcah Langley\Desktop\Luna-Grabber-main\luna.py", line 83, in main
    requests.post(webhook, json=data)
  File "C:\Users\New MIcah Langley\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\New MIcah Langley\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\New MIcah Langley\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\New MIcah Langley\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 484, in prepare_request
    p.prepare(
  File "C:\Users\New MIcah Langley\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "C:\Users\New MIcah Langley\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?

**Comment by Smug246** [comment]
no webhook was added. make sure you add a webhook first then press check webhook
