### ISSUE TITLE
Not building

### ISSUE THREAD

**Issue by BridgeKeeper1** [Smug246/Luna-Grabber#184]
what it says when i try to build 
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Sean Reznik\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\Sean Reznik\AppData\Local\Programs\Python\Python310\lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 553, in _clicked
    self._command()
  File "C:\Users\Sean Reznik\Downloads\Luna-Grabber-main\Luna-Grabber-main\builder.pyw", line 459, in buildfile
    self.write_and_obfuscate(filename)
  File "C:\Users\Sean Reznik\Downloads\Luna-Grabber-main\Luna-Grabber-main\builder.pyw", line 438, in write_and_obfuscate
    with open(f"./{filename}.py", 'w', encoding="utf-8") as f:
PermissionError: [Errno 13] Permission denied: './test.py'

**Comment by Smug246** [comment]
also can you check the permissions of the directory where the file is being created by right-clicking on the folder and selecting "Properties". In the Properties dialog, go to the "Security" tab and check if you have "Write" permission. if not screenshot what it says
