### ISSUE TITLE
what is that error?

### ISSUE THREAD

**Issue by Waltuhy** [Smug246/Luna-Grabber#198]
Traceback (most recent call last): File "lunarpoc.py", line 1011, in <module> File "lunarpoc.py", line 86, in Luna File "lunarpoc.py", line 61, in main File "requests\api.py", line 115, in post File "requests\api.py", line 59, in request File "requests\sessions.py", line 573, in request File "requests\sessions.py", line 484, in prepare_request File "requests\models.py", line 368, in prepare File "requests\models.py", line 439, in prepare_url requests.exceptions.MissingSchema: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?

**Comment by Smug246** [comment]
it means a webhook wasnt added

**Comment by Pluzdev** [comment]
Hi, i think not:
```
Traceback (most recent call last):
  File "trythisshit.py", line 1, in <module>
  File "<string>", line 4, in <module>
  File "<string>", line 1, in <module>
  File "<string>", line 1011, in <module>
  File "<string>", line 86, in Luna
  File "<string>", line 61, in main
  File "requests\api.py", line 115, in post
  File "requests\api.py", line 59, in request
  File "requests\sessions.py", line 573, in request
  File "requests\sessions.py", line 484, in prepare_request
  File "requests\models.py", line 368, in prepare
  File "requests\models.py", line 439, in prepare_url
requests.exceptions.MissingSchema: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?
```
I got the same error, but i puted a valid webhook on the box:
![image](https://user-images.githubusercontent.com/64200318/231889763-8b89239a-d7f0-4f54-a038-e8cd1e108ee6.png)

**Comment by Pluzdev** [comment]
Maybe i'm doing something bad

**Comment by Smug246** [comment]
do you input the webhook and press check webhook before you do anything else?

**Comment by Smug246** [comment]
latest version i fixed this run setup.bat and it will download it for you
