### ISSUE TITLE
Error when starting in another PC

### ISSUE THREAD

**Issue by thegamerchris444** [Smug246/Luna-Grabber#213]
When using the exe on another pc transported from usb you get the following error:

Traceback (most recent call last):
  File "Test01.py", line 1, in <module>
  File "<string>", line 4, in <module>
  File "<string>", line 1, in <module>
  File "<string>", line 1027, in <module>
  File "<string>", line 86, in Luna
  File "<string>", line 61, in main
  File "requests\api.py", line 115, in post
  File "requests\api.py", line 59, in request
  File "requests\sessions.py", line 573, in request
  File "requests\sessions.py", line 484, in prepare_request
  File "requests\models.py", line 368, in prepare
  File "requests\models.py", line 439, in prepare_url
requests.exceptions.MissingSchema: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?

**Comment by Smug246** [comment]
this means no webhook has been added build with the latest version where this if fixed

**Comment by thegamerchris444** [comment]
I cant even create the exe file

**Comment by Smug246** [comment]
you problem if you cant provide me an error
