### ISSUE TITLE
The file wont build

### ISSUE THREAD

**Issue by nyx-ui** [Smug246/Luna-Grabber#240]
When i want to build the file (pyinstaller) it does not build and gives me this error:

pyinstaller
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\customtkinter\windows\widgets\ctk_button.py", line 553, in _clicked
    self._command()
  File "C:\Users\Admin\Downloads\Luna-Grabber-main\builder.pyw", line 493, in buildfile
    self.write_and_obfuscate(filename)
  File "C:\Users\Admin\Downloads\Luna-Grabber-main\builder.pyw", line 473, in write_and_obfuscate
    f.write(self.get_config())
  File "C:\Users\Admin\Downloads\Luna-Grabber-main\builder.pyw", line 392, in get_config
    with open(self.basefilepath + "\\luna.py", 'r', encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Admin\\Downloads\\Luna-Grabber-main\\luna.py'

![image](https://user-images.githubusercontent.com/120686440/233786470-25da0cc7-16a8-4565-8c4f-0005eb1af0de.png)
![image](https://user-images.githubusercontent.com/120686440/233786486-da148915-e518-47d4-b374-73a8ca714c65.png)

**Comment by Smug246** [comment]
looks like u didnt extract the file onto ur desktop

**Comment by nyx-ui** [comment]
oh yeah, i had it in my downloads folder. Thanks
