### ISSUE TITLE
WinError: The system cannot find the file specified

### ISSUE THREAD

**Issue by kyan0045** [Smug246/Luna-Grabber#248]
**Describe the bug**

**To Reproduce**
Create cxfreeze grabber

**Expected behavior**
Work

**Screenshots**

**Additional context**
```
Exception in thread Thread-1 (compile_file):
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\gener\Downloads\Luna-Grabber-main\Luna-Grabber-main\builder.pyw", line 450, in compile_file
    subprocess.run(cmd_args)
  File "C:\Program Files\Python311\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Python311\Lib\subprocess.py", line 1493, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by Smug246** [comment]
latest version
