### ISSUE TITLE
Execution error

### ISSUE THREAD

**Issue by theprospence** [Smug246/Luna-Grabber#251]
I am getting an execution error when I'm running the exe file.

Traceback (most recent call last):
  File "ol.py", line 1, in <module>
  File "<string>", line 4, in <module>
  File "<string>", line 1, in <module>
  File "<string>", line 17, in <module>
ModuleNotFoundError: No module named 'Crypto'

How do I fix this?

**Comment by crazyffuck** [comment]
you cant use .exe's anymore if you read the code, so reinstall it and get the new ones with cxfreeze, pyinstaller and py

**Comment by Smug246** [comment]
in the latest version i fixed this
