### ISSUE TITLE
Pid Closing error

### ISSUE THREAD

**Issue by BridgeKeeper1** [Smug246/Luna-Grabber#344]
Traceback (most recent call last):                                                                                        File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\psutil\_pswindows.py", line 694, in wrapper                                                                                                                          return fun(self, *args, **kwargs)                                                                                     File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\psutil\_pswindows.py", line 878, in kill     return cext.proc_kill(self.pid)                                                                                     PermissionError: [WinError 5] Access is denied: '(originated from OpenProcess)'                                                                                                                                                                 During handling of the above exception, another exception occurred:                                                                                                                                                                             Traceback (most recent call last):                                                                                        File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\threading.py", line 954, in _bootstrap_inner               self.run()                                                                                                            File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\threading.py", line 892, in run                            self._target(*self._args, **self._kwargs)                                                                             File "C:\Users\User\Downloads\Luna-Grabber-main\Luna-Grabber-main\test.py", line 571, in __init__                         proc.kill()                                                                                                           File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\psutil\__init__.py", line 278, in wrapper    return fun(self, *args, **kwargs)                                                                                     File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\psutil\__init__.py", line 1250, in kill      self._proc.kill()                                                                                                     File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\psutil\_pswindows.py", line 696, in wrapper                                                                                                                          raise convert_oserror(err, pid=self.pid, name=self._name)                                                           psutil.AccessDenied: (pid=5220, name='chrome.exe')

**Comment by Smug246** [comment]
fixed
