### ISSUE TITLE
no work xd

### ISSUE THREAD

**Issue by 8FrMc** [Smug246/Luna-Grabber#364]
Traceback (most recent call last):
  File "requests_toolbelt\_compat.py", line 48, in <module>
ImportError: cannot import name 'appengine' from 'requests.packages.urllib3.contrib' (C:\Users\pc\AppData\Local\Temp\_MEI146802\urllib3\contrib\__init__.pyc)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hi.py", line 5, in <module>
  File "<string>", line 1, in <module>
  File "<string>", line 21, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "requests_toolbelt\__init__.py", line 12, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "requests_toolbelt\adapters\__init__.py", line 12, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "requests_toolbelt\adapters\ssl.py", line 16, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "requests_toolbelt\_compat.py", line 50, in <module>
ImportError: cannot import name 'appengine' from 'urllib3.contrib' (C:\Users\pc\AppData\Local\Temp\_MEI146802\urllib3\contrib\__init__.pyc)
using pyintaller obf

**Comment by Smug246** [comment]
have u got the latest version of python and that module
