### ISSUE TITLE
[ERROR] 

### ISSUE THREAD

**Issue by MrShadowDev** [Smug246/Luna-Grabber#365]
```Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\usuario\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\usuario\AppData\Local\Programs\Python\Python310\lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 531, in _clicked
    self._command()
  File "D:\Tools\Luna-Grabber\builder.pyw", line 531, in buildfile
    self.file_pumper(filename, "exe", self.get_mb())
  File "D:\Tools\Luna-Grabber\builder.pyw", line 423, in file_pumper
    with open(f"./{filename}.{extension}", 'ab') as f:
PermissionError: [Errno 13] Permission denied: './kurumi.exe'```


It gives me this error in the cmd:

![image](https://github.com/Smug246/Luna-Grabber/assets/71973368/e06e82d4-6a9c-4746-a5ab-aa7db0b0d2cb)

**Comment by Smug246** [comment]
latest version
