### ISSUE TITLE
hm it is not bug and it is error of python

### ISSUE THREAD

**Issue by Ryder2048** [Smug246/Luna-Grabber#445]
Traceback (most recent call last):
  File "urllib3\connection.py", line 203, in _new_conn
  File "urllib3\util\connection.py", line 60, in create_connection
  File "socket.py", line 962, in getaddrinfo
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 790, in urlopen
  File "urllib3\connectionpool.py", line 491, in _make_request
  File "urllib3\connectionpool.py", line 467, in _make_request
  File "urllib3\connectionpool.py", line 1092, in _validate_conn
  File "urllib3\connection.py", line 611, in connect
  File "urllib3\connection.py", line 210, in _new_conn
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x000001A111CEA490>: Failed to resolve 'api.ipify.org' ([Errno 11001] getaddrinfo failed)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "requests\adapters.py", line 486, in send
  File "urllib3\connectionpool.py", line 844, in urlopen
  File "urllib3\util\retry.py", line 515, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001A111CEA490>: Failed to resolve 'api.ipify.org' ([Errno 11001] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "xbox_copyR.py", line 5, in <module>
  File "<string>", line 1, in <module>
  File "<string>", line 999, in <module>
  File "<string>", line 75, in Luna
  File "<string>", line 871, in __init__
  File "<string>", line 955, in checks
  File "<string>", line 972, in get_network
  File "requests\api.py", line 73, in get
  File "requests\api.py", line 59, in request
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 519, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001A111CEA490>: Failed to resolve 'api.ipify.org' ([Errno 11001] getaddrinfo failed)"))

I am using python 3.11.4/window/using nord vpn

**Comment by Smug246** [comment]
try typing that url into your browser and tell me if it loads. api.ipify.org
