### ISSUE TITLE
error when executing the .exe file

### ISSUE THREAD

**Issue by mankygames** [Smug246/Luna-Grabber#612]
getting that error when trying to execute the file:

Traceback (most recent call last):
  File "terere.py", line 5, in <module>
  File "<string>", line 1, in <module>
  File "<string>", line 13, in <module>
ImportError: cannot import name 'wintypes' from 'ctypes' (C:\Users\A\AppData\Local\Temp\_MEI83162\ctypes\__init__.pyc)

**Comment by benjifoxy** [comment]
Same issue here - I even tried using older versions and it's still coming back with the same error
