### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by loneeps** [Smug246/Luna-Grabber#747]
### What Did You Expect To Happen?

to build the file correct

### What Happened?

when I make a file it doesnt show any errors, but theres nothing in the file like its blank

### Add Screenshots

![image](https://github.com/Smug246/Luna-Grabber/assets/127301375/4bf37076-4097-42b8-8932-956b2350deb8)

### Which Options Did You Select?

Add To Startup, Disable Defender, Discord Info, Kill Protector, Wifi Info, Ping, Anti Debug/VM, Minecraft Info, System Info, 2FA Codes, Browser Info, Roblox Info, Obfuscation, Injection, Anti Spam, Self Destruct, File Pumper, Clipboard

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [X] I have attempted to resolve my problem by myself

**Comment by Smug246** [comment]
did you use pyinstaller or nuitka

**Comment by loneeps** [comment]
pyinstaller and when I use .py it shows it blank

**Comment by Smug246** [comment]
can you try and paste the whole error so i can see it all

**Comment by loneeps** [comment]
OFC! here you go: 
.py file: "Error with writing and obfuscating file: write() argument must be str, not None"
.pyinstaller: "Checking for updates...
This version is up to date!
Setup Complete
Starting the builder...
Error with writing and obfuscating file: write() argument must be str, not None
Error with writing and obfuscating file: write() argument must be str, not None
137 INFO: PyInstaller: 6.6.0, contrib hooks: 2024.5
137 INFO: Python: 3.12.2
149 INFO: Platform: Windows-10-10.0.19045-SP0
150 INFO: wrote C:\Users\G-186917268\Documents\LunaGrabber\zay.spec
164 INFO: UPX is available and will be used if enabled on build targets.
164 INFO: Removing temporary files and cleaning cache in C:\Users\G-186917268\AppData\Local\pyinstaller
171 INFO: Extending PYTHONPATH with paths
['C:\\Users\\G-186917268\\Documents\\LunaGrabber']
283 INFO: checking Analysis
283 INFO: Building Analysis because Analysis-00.toc is non existent
283 INFO: Running Analysis Analysis-00.toc
283 INFO: Target bytecode optimization level: 0
283 INFO: Initializing module dependency graph...
283 INFO: Caching module graph hooks...
289 INFO: Analyzing base_library.zip ...
1037 INFO: Loading module hook 'hook-encodings.py' from 'C:\\Users\\G-186917268\\Documents\\LunaGrabber\\.venv_3.12.2\\Lib\\site-packages\\PyInstaller\\hooks'...
1858 INFO: Loading module hook 'hook-pickle.py' from 'C:\\Users\\G-186917268\\Documents\\LunaGrabber\\.venv_3.12.2\\Lib\\site-packages\\PyInstaller\\hooks'...
2339 INFO: Loading module hook 'hook-heapq.py' from 'C:\\Users\\G-186917268\\Documents\\LunaGrabber\\.venv_3.12.2\\Lib\\site-packages\\PyInstaller\\hooks'...
2547 INFO: Caching module dependency graph...
2610 INFO: Looking for Python shared library...
2612 INFO: Using Python shared library: C:\Users\G-186917268\AppData\Local\Programs\Python\Python312\python312.dll
2612 INFO: Analyzing C:\Users\G-186917268\Documents\LunaGrabber\zay.py
2613 INFO: Analyzing hidden import 'json'
2628 INFO: Analyzing hidden import 'requests_toolbelt'
2737 INFO: Loading module hook 'hook-platform.py' from 'C:\\Users\\G-186917268\\Documents\\LunaGrabber\\.venv_3.12.2\\Lib\\site-packages\\PyInstaller\\hooks'...
3080 INFO: Loading module hook 'hook-charset_normalizer.py' from 'C:\\Users\\G-186917268\\Documents\\LunaGrabber\\.venv_3.12.2\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
3239 INFO: Loading module hook 'hook-cryptography.py' from 'C:\\Users\\G-186917268\\Documents\\LunaGrabber\\.venv_3.12.2\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
3937 INFO: Loading module hook 'hook-certifi.py' from 'C:\\Users\\G-186917268\\Documents\\LunaGrabber\\.venv_3.12.2\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
4027 INFO: Analyzing hidden import 'psutil'
4051 INFO: Loading module hook 'hook-psutil.py' from 'C:\\Users\\G-186917268\\Documents\\LunaGrabber\\.venv_3.12.2\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
4100 INFO: Analyzing hidden import 'sqlite3'
4101 INFO: Loading module hook 'hook-sqlite3.py' from 'C:\\Users\\G-186917268\\Documents\\LunaGrabber\\.venv_3.12.2\\Lib\\site-packages\\PyInstaller\\hooks'...
4268 INFO: Analyzing hidden import 'win32crypt'
4269 INFO: Analyzing hidden import 'Cryptodome.Cipher.AES'
4271 INFO: Loading module hook 'hook-Cryptodome.py' from 'C:\\Users\\G-186917268\\Documents\\LunaGrabber\\.venv_3.12.2\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
4517 INFO: Loading module hook 'hook-pycparser.py' from 'C:\\Users\\G-186917268\\Documents\\LunaGrabber\\.venv_3.12.2\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
4727 INFO: Loading module hook 'hook-setuptools.py' from 'C:\\Users\\G-186917268\\Documents\\LunaGrabber\\.venv_3.12.2\\Lib\\site-packages\\PyInstaller\\hooks'...
5487 INFO: Processing pre-safe import module hook distutils from 'C:\\Users\\G-186917268\\Documents\\LunaGrabber\\.venv_3.12.2\\Lib\\site-packages\\PyInstaller\\hooks\\pre_safe_import_module\\hook-distutils.py'.
5856 INFO: Loading module hook 'hook-distutils.py' from 'C:\\Users\\G-186917268\\Documents\\LunaGrabber\\.venv_3.12.2\\Lib\\site-packages\\PyInstaller\\hooks'...
5858 INFO: Loading module hook 'hook-distutils.util.py' from 'C:\\Users\\G-186917268\\Documents\\LunaGrabber\\.venv_3.12.2\\Lib\\site-packages\\PyInstaller\\hooks'...
5890 INFO: Loading module hook 'hook-setuptools.msvc.py' from 'C:\\Users\\G-186917268\\Documents\\LunaGrabber\\.venv_3.12.2\\Lib\\site-packages\\PyInstaller\\hooks'...
6004 INFO: Loading module hook 'hook-packaging.py' from 'C:\\Users\\G-186917268\\Documents\\LunaGrabber\\.venv_3.12.2\\Lib\\site-packages\\PyInstaller\\hooks'...
6062 INFO: Loading module hook 'hook-sysconfig.py' from 'C:\\Users\\G-186917268\\Documents\\LunaGrabber\\.venv_3.12.2\\Lib\\site-packages\\PyInstaller\\hooks'...
6351 INFO: Loading module hook 'hook-pkg_resources.py' from 'C:\\Users\\G-186917268\\Documents\\LunaGrabber\\.venv_3.12.2\\Lib\\site-packages\\PyInstaller\\hooks'...
6879 INFO: Loading module hook 'hook-xml.py' from 'C:\\Users\\G-186917268\\Documents\\LunaGrabber\\.venv_3.12.2\\Lib\\site-packages\\PyInstaller\\hooks'...
7085 INFO: Analyzing hidden import 'PIL.ImageGrab'
7086 INFO: Loading module hook 'hook-PIL.py' from 'C:\\Users\\G-186917268\\Documents\\LunaGrabber\\.venv_3.12.2\\Lib\\site-packages\\PyInstaller\\hooks'...
7141 INFO: Loading module hook 'hook-PIL.Image.py' from 'C:\\Users\\G-186917268\\Documents\\LunaGrabber\\.venv_3.12.2\\Lib\\site-packages\\PyInstaller\\hooks'...
7511 INFO: Loading module hook 'hook-PIL.ImageFilter.py' from 'C:\\Users\\G-186917268\\Documents\\LunaGrabber\\.venv_3.12.2\\Lib\\site-packages\\PyInstaller\\hooks'...
7523 INFO: Analyzing hidden import 'pyperclip'
7538 INFO: Analyzing hidden import 'cv2'
7539 ERROR: Hidden import 'cv2' not found
7539 INFO: Processing module hooks...
7540 INFO: Loading module hook 'hook-distutils.command.check.py' from 'C:\\Users\\G-186917268\\Documents\\LunaGrabber\\.venv_3.12.2\\Lib\\site-packages\\PyInstaller\\hooks'...
7696 INFO: Loading module hook 'hook-PIL.SpiderImagePlugin.py' from 'C:\\Users\\G-186917268\\Documents\\LunaGrabber\\.venv_3.12.2\\Lib\\site-packages\\PyInstaller\\hooks'...
8228 INFO: Loading module hook 'hook-difflib.py' from 'C:\\Users\\G-186917268\\Documents\\LunaGrabber\\.venv_3.12.2\\Lib\\site-packages\\PyInstaller\\hooks'...
8328 INFO: Loading module hook 'hook-multiprocessing.util.py' from 'C:\\Users\\G-186917268\\Documents\\LunaGrabber\\.venv_3.12.2\\Lib\\site-packages\\PyInstaller\\hooks'...
8962 INFO: Loading module hook 'hook-setuptools._distutils.command.check.py' from 'C:\\Users\\G-186917268\\Documents\\LunaGrabber\\.venv_3.12.2\\Lib\\site-packages\\PyInstaller\\hooks'...
9143 INFO: Performing binary vs. data reclassification (54 entries)
9157 INFO: Looking for ctypes DLLs
9174 INFO: Analyzing run-time hooks ...
9177 INFO: Including run-time hook 'C:\\Users\\G-186917268\\Documents\\LunaGrabber\\.venv_3.12.2\\Lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_inspect.py'
9178 INFO: Including run-time hook 'C:\\Users\\G-186917268\\Documents\\LunaGrabber\\.venv_3.12.2\\Lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pkgres.py'
9181 INFO: Including run-time hook 'C:\\Users\\G-186917268\\Documents\\LunaGrabber\\.venv_3.12.2\\Lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pkgutil.py'
9183 INFO: Processing pre-find module path hook _pyi_rth_utils from 'C:\\Users\\G-186917268\\Documents\\LunaGrabber\\.venv_3.12.2\\Lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-_pyi_rth_utils.py'.
9184 INFO: Loading module hook 'hook-_pyi_rth_utils.py' from 'C:\\Users\\G-186917268\\Documents\\LunaGrabber\\.venv_3.12.2\\Lib\\site-packages\\PyInstaller\\hooks'...
9185 INFO: Including run-time hook 'C:\\Users\\G-186917268\\Documents\\LunaGrabber\\.venv_3.12.2\\Lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_setuptools.py'
9185 INFO: Including run-time hook 'C:\\Users\\G-186917268\\Documents\\LunaGrabber\\.venv_3.12.2\\Lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_multiprocessing.py'
9188 INFO: Including run-time hook 'C:\\Users\\G-186917268\\Documents\\LunaGrabber\\.venv_3.12.2\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\rthooks\\pyi_rth_cryptography_openssl.py'
9195 INFO: Looking for dynamic libraries
9506 INFO: Extra DLL search directories (AddDllDirectory): []
9506 INFO: Extra DLL search directories (PATH): []
9750 INFO: Warnings written to C:\Users\G-186917268\Documents\LunaGrabber\build\zay\warn-zay.txt
9792 INFO: Graph cross-reference written to C:\Users\G-186917268\Documents\LunaGrabber\build\zay\xref-zay.html
9811 INFO: checking PYZ
9812 INFO: Building PYZ because PYZ-00.toc is non existent
9812 INFO: Building PYZ (ZlibArchive) C:\Users\G-186917268\Documents\LunaGrabber\build\zay\PYZ-00.pyz
10493 INFO: Building PYZ (ZlibArchive) C:\Users\G-186917268\Documents\LunaGrabber\build\zay\PYZ-00.pyz completed successfully.
10505 INFO: checking PKG
10506 INFO: Building PKG because PKG-00.toc is non existent
10506 INFO: Building PKG (CArchive) zay.pkg
10519 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\python312.dll
12124 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\Cryptodome\Cipher\_raw_des3.pyd
12153 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\Cryptodome\Cipher\_raw_ocb.pyd
12171 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\Cryptodome\Hash\_SHA512.pyd
12191 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\Cryptodome\Math\_modexp.pyd
12211 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\Cryptodome\Cipher\_raw_blowfish.pyd
12231 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\Cryptodome\PublicKey\_ec_ws.pyd
12398 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\Cryptodome\Util\_strxor.pyd
12414 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\Cryptodome\Cipher\_chacha20.pyd
12432 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\Cryptodome\Hash\_SHA384.pyd
12453 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\Cryptodome\Protocol\_scrypt.pyd
12471 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\Cryptodome\Cipher\_raw_ctr.pyd
12488 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\Cryptodome\Hash\_MD5.pyd
12507 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\Cryptodome\Cipher\_pkcs1_decode.pyd
12525 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\Cryptodome\Cipher\_raw_aesni.pyd
12543 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\Cryptodome\Cipher\_raw_ecb.pyd
12559 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\Cryptodome\PublicKey\_ed448.pyd
12586 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\Cryptodome\Hash\_ghash_clmul.pyd
12604 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\Cryptodome\Util\_cpuid_c.pyd
12621 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\Cryptodome\Hash\_BLAKE2b.pyd
12639 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\Cryptodome\Cipher\_raw_cbc.pyd
12656 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\Cryptodome\Hash\_RIPEMD160.pyd
12675 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\Cryptodome\Cipher\_Salsa20.pyd
12693 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\Cryptodome\PublicKey\_ed25519.pyd
12712 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\Cryptodome\Hash\_MD2.pyd
12730 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\Cryptodome\Hash\_SHA256.pyd
12749 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\Cryptodome\Cipher\_raw_cast.pyd
12768 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\Cryptodome\Hash\_BLAKE2s.pyd
12786 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\Cryptodome\Cipher\_raw_cfb.pyd
12804 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\Cryptodome\Hash\_ghash_portable.pyd
12821 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\Cryptodome\Cipher\_ARC4.pyd
12837 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\Cryptodome\PublicKey\_x25519.pyd
12854 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\Cryptodome\Hash\_keccak.pyd
12871 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\Cryptodome\Hash\_SHA1.pyd
12891 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\Cryptodome\Cipher\_raw_ofb.pyd
12908 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\Cryptodome\Cipher\_raw_aes.pyd
12929 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\Cryptodome\Hash\_poly1305.pyd
12947 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\Cryptodome\Cipher\_raw_eksblowfish.pyd
12966 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\Cryptodome\Hash\_MD4.pyd
12984 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\Cryptodome\Cipher\_raw_des.pyd
13014 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\Cryptodome\Hash\_SHA224.pyd
13033 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\Cryptodome\Cipher\_raw_arc2.pyd
13052 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\select.pyd
13070 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\_hashlib.pyd
13095 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\_lzma.pyd
13138 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\_bz2.pyd
13166 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\pyexpat.pyd
13217 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\_ssl.pyd
13265 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\unicodedata.pyd
13493 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\_decimal.pyd
13554 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\_multiprocessing.pyd
13574 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\_socket.pyd
13603 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\_ctypes.pyd
13640 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\_queue.pyd
13658 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\_wmi.pyd
13678 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\win32\win32api.pyd
13719 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\_overlapped.pyd
13741 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\_asyncio.pyd
13768 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\PIL\_webp.cp312-win_amd64.pyd
13865 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\PIL\_imagingtk.cp312-win_amd64.pyd
13884 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\PIL\_imagingcms.cp312-win_amd64.pyd
13949 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\PIL\_imagingmath.cp312-win_amd64.pyd
13969 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\_cffi_backend.cp312-win_amd64.pyd
14024 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\PIL\_imaging.cp312-win_amd64.pyd
14522 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\win32\win32crypt.pyd
14560 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\_sqlite3.pyd
14598 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\psutil\_psutil_windows.pyd
14627 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\zstandard\_cffi.cp312-win_amd64.pyd
14768 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\zstandard\backend_c.cp312-win_amd64.pyd
14894 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\cryptography\hazmat\bindings\_rust.pyd
16712 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\charset_normalizer\md__mypyc.cp312-win_amd64.pyd
16749 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\charset_normalizer\md.cp312-win_amd64.pyd
16767 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\_uuid.pyd
16782 WARNING: Failed to upx strip on 'C:\\Users\\G-186917268\\AppData\\Local\\pyinstaller\\bincache01py31264bit\\_uuid.pyd'!
Traceback (most recent call last):
  File "C:\Users\G-186917268\Documents\LunaGrabber\.venv_3.12.2\Lib\site-packages\PyInstaller\building\utils.py", line 283, in process_collected_binary
    p = subprocess.run(
        ^^^^^^^^^^^^^^^
  File "C:\Users\G-186917268\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['./tools\\upx', '--compress-icons=0', '--lzma', '-q', '--strip-loadconf', 'C:\\Users\\G-186917268\\AppData\\Local\\pyinstaller\\bincache01py31264bit\\_uuid.pyd']' returned non-zero exit status 1.
16782 WARNING: Output from upx command:
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2024
UPX 4.2.4       Markus Oberhumer, Laszlo Molnar & John Reiser    May 9th 2024

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx: C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\_uuid.pyd: NotCompressibleException

Packed 1 file: 0 ok, 1 error.

16784 INFO: Disabling UPX for C:\Users\G-186917268\AppData\Local\Programs\Python\Python312\VCRUNTIME140.dll due to CFG!
16794 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\libcrypto-3.dll
17936 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\libssl-3.dll
18093 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\libffi-8.dll
18114 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\pywin32_system32\pywintypes312.dll
18151 INFO: Disabling UPX for C:\Users\G-186917268\AppData\Local\Programs\Python\Python312\VCRUNTIME140_1.dll due to CFG!
18155 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\sqlite3.dll
18532 INFO: Executing: ./tools\upx --compress-icons=0 --lzma -q --strip-loadconf C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\python3.dll
18548 WARNING: Failed to upx strip on 'C:\\Users\\G-186917268\\AppData\\Local\\pyinstaller\\bincache01py31264bit\\python3.dll'!
Traceback (most recent call last):
  File "C:\Users\G-186917268\Documents\LunaGrabber\.venv_3.12.2\Lib\site-packages\PyInstaller\building\utils.py", line 283, in process_collected_binary
    p = subprocess.run(
        ^^^^^^^^^^^^^^^
  File "C:\Users\G-186917268\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['./tools\\upx', '--compress-icons=0', '--lzma', '-q', '--strip-loadconf', 'C:\\Users\\G-186917268\\AppData\\Local\\pyinstaller\\bincache01py31264bit\\python3.dll']' returned non-zero exit status 1.
18548 WARNING: Output from upx command:
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2024
UPX 4.2.4       Markus Oberhumer, Laszlo Molnar & John Reiser    May 9th 2024

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx: C:\Users\G-186917268\AppData\Local\pyinstaller\bincache01py31264bit\python3.dll: NotCompressibleException

Packed 1 file: 0 ok, 1 error.

18920 INFO: Building PKG (CArchive) zay.pkg completed successfully.
18922 INFO: Bootloader C:\Users\G-186917268\Documents\LunaGrabber\.venv_3.12.2\Lib\site-packages\PyInstaller\bootloader\Windows-64bit-intel\runw.exe
18922 INFO: checking EXE
18922 INFO: Building EXE because EXE-00.toc is non existent
18923 INFO: Building EXE from EXE-00.toc
18923 INFO: Copying bootloader EXE to C:\Users\G-186917268\Documents\LunaGrabber\zay.exe
18925 INFO: Copying 0 resources to EXE
18925 INFO: Embedding manifest in EXE
18927 INFO: Appending PKG archive to EXE
18933 INFO: Fixing EXE headers
18998 INFO: Building EXE from EXE-00.toc completed successfully."

**Comment by Smug246** [comment]
can you also copy the last like 30 lines from the luna.log file

**Comment by loneeps** [comment]
yeah but do you have discord so I can sent u it there cause there is my webhook and I dont want people to spam it heres my discord: k3peez

**Comment by Smug246** [comment]
id prefer if you dm'd me via telegram: t.me/lunaxsmug

**Comment by loneeps** [comment]
yeah sure ill install it :)

**Comment by loneeps** [comment]
ive installed it how do I message you? :>

**Comment by Smug246** [comment]
fixed this over on telegram. antivirus deleted a file which just needed reinstalling
